spring:
  application:
    name: vdenise-advanced-todo
  datasource:
    url: jdbc:h2:mem:todo
    username: h2
    password: h2
    platform: h2

logging:
  level:
    root: DEBUG

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /ui